version: "3.9"
services:
  db:
    image: postgres:14.7-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: wassup_news_production

  redis:
    image: redis:7.0-alpine

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://postgres:secret@db/wassup_news_production
      REDIS_URL: redis://redis:6379/0
volumes:
  db_data:
